# Generated by Django 2.2 on 2019-04-18 21:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TechReviewApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reivew',
            new_name='Review',
        ),
    ]
